version: '2.1'
services:
     elasticsearch:
       image: elasticsearch:7.6.2
       container_name: ddd_elasticsearch
       volumes:
           - data01:/usr/share/elasticsearch/data
       environment:
           - discovery.type=single-node
       networks:
           docker-elk:
       ports:
           - 9200:9200

     kibana:
       image: kibana:7.6.2
       container_name: ddd_kibana
       environment:
           - "ELASTICSEARCH_URL=http://elasticsearch:9200"
       networks:
           - docker-elk
       ports:
           - 5601:5601
       depends_on:
           - elasticsearch
    
volumes:
    data01:
        driver: local
networks:
    docker-elk:
        driver: bridge
